// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6clwxAZ5PMBZEUrQXX7NtEPNiDnjxCF4',
    appId: '1:812209006929:web:b7b8cd03228a65c98acb70',
    messagingSenderId: '812209006929',
    projectId: 'attendance-app-1d5d9',
    authDomain: 'attendance-app-1d5d9.firebaseapp.com',
    storageBucket: 'attendance-app-1d5d9.appspot.com',
    measurementId: 'G-WT9Q1EMBP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdu5sV2ut_X1RC2e6L6_ECQZMVkoKa6kc',
    appId: '1:812209006929:android:82e17be97a700b168acb70',
    messagingSenderId: '812209006929',
    projectId: 'attendance-app-1d5d9',
    storageBucket: 'attendance-app-1d5d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaoCt58rlR8gY944fuirj4uVtqGqOtU-I',
    appId: '1:812209006929:ios:f6cf4c10ea58992c8acb70',
    messagingSenderId: '812209006929',
    projectId: 'attendance-app-1d5d9',
    storageBucket: 'attendance-app-1d5d9.appspot.com',
    iosClientId: '812209006929-b64cink00q03q6t9sf0chjscagpuovcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaoCt58rlR8gY944fuirj4uVtqGqOtU-I',
    appId: '1:812209006929:ios:e93e42dd01f9a4a28acb70',
    messagingSenderId: '812209006929',
    projectId: 'attendance-app-1d5d9',
    storageBucket: 'attendance-app-1d5d9.appspot.com',
    iosClientId: '812209006929-7irqq686b6c5t0jr4v30buegj6soe2o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp.RunnerTests',
  );
}
